---
title: "3.2_Figures"
author: "Florian van Leeuwen"
date: "2023-02-15"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include = F}
library(tidyverse)
library(patchwork)
library(segmented)
```

```{r}
# import fucntion to set the color of the plots to the same scale
source("Functions/4.Set_scale_equal.R")
```

## Visualisation of the simulattion scnearios

```{r}
# figure of the setup of the simulation study
time <- rep(seq(10),4)
group <- c(rep("Step", 10), rep("Slope", 10), rep("Step and slope", 10), rep("Two steps and slope", 10))
score1 <- time * 2 + c(rep(0,5), rep(-2,5), rep(0,5), -0.5, -1.2, -2.2, -3.2, -4.2, rep(0, 5), 
                       -3, -4.5, -6, -7.5, -9, rep(0, 5), -4, -5.5, -9, -10.5, -12)

data_eex <- data.frame(time = time, 
            group = group,
            score = score1)

data_eex %>% 
  ggplot(aes(x = time, y = score)) +
  geom_point() +
  geom_segment(aes(x = 1, y = 2, xend = 5.5, yend = 11, color = "General trend")) +
  geom_segment(aes(x = 5.5, y = 9, xend = 10, yend = 18, color = "Step")) +
  geom_segment(aes(x = 5.5, y = 11, xend = 10, yend = 16, color = "Slope")) +
  geom_segment(aes(x = 5.5, y = 8.75, xend = 10, yend = 11, color = "Step and slope")) +
  geom_segment(aes(x = 5.5, y = 7.75, xend = 7.5, yend = 8.75, color = "Two steps and slope")) +
  geom_segment(aes(x = 7.5, y = 6.75, xend = 10, yend = 8, color = "Two steps and slope")) +
  scale_color_discrete(name="Changing parameter") +
  labs(y = "Score", x = "Time") +
  geom_vline(xintercept = 5.5, linetype = "dashed") +
  geom_vline(xintercept = 7.5, linetype = "dotted") +
  scale_x_continuous("Time", labels=c("T_0", "(N+1)/2","3(N+1)/4", "T_N"), breaks=c(1, 5.5, 7.5, 10)) +
  theme_minimal()

ggsave("2. Simulation study/Output/figures/sim_setup2.png", width = 7, height = 5 )
```

## READ in the data
```{r}
# import the data
out10 <- read.csv("Output/results/sim10_final.csv")
out01 <- read.csv("Output/results/sim01_final.csv")
out11 <- read.csv("Output/results/sim11_final.csv")
out11_additional_step <- read.csv("Output/results/out11_additional_step_final.csv")
out11_additional_step_corr <- read.csv("Output/results/out11_additional_step_corr_final.csv")
out_time_2 <- read.csv("Output/results/time2_final.csv")
```

### Select scenario
```{r}
df <- out11_additional_step_corr
```

#### Power
```{r}
p1 <- df %>% 
  ggplot(aes(x = N_t, y = N_pers, fill = pre_slope)) +
  geom_tile() + 
  labs(x = "Number of time points",
       y = "Number of participants", fill="Power") +
  facet_wrap(~effect_sizes) +
  theme_minimal() 

p2 <- df %>% 
  ggplot(aes(x = N_t, y = N_pers, fill = step)) +
  geom_tile() + 
  labs(x = "Number of time points",
       y = "Number of participants", fill="Power") +
  facet_wrap(~effect_sizes) +
  theme_minimal() 

p3 <- df %>% 
  ggplot(aes(x = N_t, y = N_pers, fill = slope)) +
  geom_tile() + 
  labs(x = "Number of time points",
       y = "Number of participants", fill="Power") +
  facet_wrap(~effect_sizes) +
  theme_minimal() 

EV_size <- c(
                    `0.01` = "0.005",
                    `0.025` = "0.0125",
                    `0.05` = "0.025",
                    `0.1` = "0.05",
                    `0.15` = "0.075",
                    `0.3` = "0.15"
                    )

p4 <- df %>% 
  ggplot(aes(x = N_t, y = N_pers, fill = step2)) +
  geom_tile() + 
  labs(x = "Number of time points",
       y = "Number of participants", fill="Power") +
  facet_wrap(~effect_sizes, labeller = as_labeller(EV_size)) +
  theme_minimal() 

set_scale_union(p2, p3,p4, scale = scale_fill_viridis_c("Power"))
 

p2
#ggsave("Output/figures/10Power_step.png")
#ggsave("Output/figures/01Power_step.png")
#ggsave("Output/figures/11Power_step.png")
#ggsave("Output/figures/additional_step_Power_step.png")
#ggsave("Output/figures/Power_time_2_step.png")
ggsave("Output/figures/out11_additional_step_corr.png")

p3

#ggsave("Output/figures/10Power_slope.png")
#ggsave("Output/figures/01Power_slope.png")
#ggsave("Output/figures/11Power_slope.png")
#ggsave("Output/figures/additional_step_Power_slope.png")
#ggsave("Output/figures/Power_time_2_slope.png")
ggsave("Output/figures/out11_additional_slope_corr.png")

p4
ggsave("Output/figures/out11_additional_step2_corr.png")

```

#### Bias

```{r, echo=F, fig.height= 4, fig.width=6}
# heat maps
b1 <- df %>% 
  ggplot(aes(x = N_t, y = N_pers, fill = bias_pre_slope)) +
  geom_tile() + 
  labs(x = "Number of time points", 
       y = "Number of participants", fill="Percentage bias") +
  facet_wrap(~effect_sizes) +
    theme_minimal()

b2 <- df %>% 
  ggplot(aes(x = N_t, y = N_pers, fill = bias_step)) +
  geom_tile() + 
  labs(x = "Number of time points", 
       y = "Number of participants", fill="Percentage bias") +
  facet_wrap(~effect_sizes) +
    theme_minimal()

b3 <- df %>% 
  ggplot(aes(x = N_t, y = N_pers, fill = bias_slope)) +
  geom_tile() + 
  labs(x = "Number of time points", 
       y = "Number of participants", fill="Percentage bias") +
  facet_wrap(~effect_sizes) +
  theme_minimal()

b4 <- df %>% 
  ggplot(aes(x = N_t, y = N_pers, fill = bias_step2)) +
  geom_tile() + 
  labs(x = "Number of time points", 
       y = "Number of participants", fill="Percentage bias") +
  facet_wrap(~effect_sizes, labeller = as_labeller(EV_size)) +
  theme_minimal()


set_scale_union(b2, b3, b4, scale = scale_fill_viridis_c("Bias", option = "A"))

b2

#ggsave("Output/figures/10bias_step.png")
#ggsave("Output/figures/01bias_step.png")
#ggsave("Output/figures/11bias_step.png")
#ggsave("Output/figures/additional_step_Bias_step.png")
#ggsave("Output/figures/Bias_time_2_step.png")
ggsave("Output/figures/out11_additional_step_corr_bias.png")

b3
#ggsave("Output/figures/10bias_slope.png")
#ggsave("Output/figures/01bias_slope.png")
#ggsave("Output/figures/11bias_slope.png")
#ggsave("Output/figures/additional_step_Bias_slope.png")
#ggsave("Output/figures/Bias_time_2_slope.png")
ggsave("Output/figures/out11_additional_slope_corr_bias.png")

b4
ggsave("Output/figures/out11_additional_step2_corr_bias.png")
```
#### Precison (SE)
```{r, echo=F, fig.height= 4, fig.width=6}
v1 <- df %>% 
  ggplot(aes(x = N_t, y = N_pers, fill = Precision_pre_slope)) +
  geom_tile() + 
  labs(x = "Number of time points", 
       y = "Number of participants", fill="SE") +
  facet_wrap(~effect_sizes) +
    theme_minimal()

v2 <- df %>% 
  ggplot(aes(x = N_t, y = N_pers, fill = Precision_step)) +
  geom_tile() + 
  labs(x = "Number of time points", 
       y = "Number of participants", fill="SE") +
  facet_wrap(~effect_sizes) +
    theme_minimal()

v3 <- df %>% 
  ggplot(aes(x = N_t, y = N_pers, fill = Precision_slope)) +
  geom_tile() + 
  labs(x = "Number of time points", 
       y = "Number of participants", fill="SE") +
  facet_wrap(~effect_sizes) +
    theme_minimal()

v4 <- df %>% 
  ggplot(aes(x = N_t, y = N_pers, fill = Precision_step2)) +
  geom_tile() + 
  labs(x = "Number of time points", 
       y = "Number of participants", fill="SE") +
  facet_wrap(~effect_sizes, labeller = as_labeller(EV_size)) +
    theme_minimal()


set_scale_union(v2, v3, v4, scale = scale_fill_viridis_c("Precision", option = "E"))

v2
#ggsave("Output/figures/10Precision_step.png")
#ggsave("Output/figures/01Precision_step.png")
#ggsave("Output/figures/11Precision_step.png")
#ggsave("Output/figures/additional_step_Precision_step.png")
#ggsave("Output/figures/Precision_time_2_step.png")
ggsave("Output/figures/out11_additional_step_corr_precision.png")

v3

#ggsave("Output/figures/10Precision_slope.png")
#ggsave("Output/figures/01Precision_slope.png")
#ggsave("Output/figures/11Precision_slope.png")
#ggsave("Output/figures/additional_step_Precision_slope.png")
#ggsave("Output/figures/Precision_time_2_slope.png")
ggsave("Output/figures/out11_additional_slope_corr_precision.png")

v4
ggsave("Output/figures/out11_additional_step2_corr_precision.png")
```

# set timepoints set and plot 
```{r}
# set timepoints set at 8 and plot the difference of power per effect size
power1 <- df %>% 
  filter(N_t == 8) %>% 
  ggplot(aes(x = N_pers,  colour = as.factor(effect_sizes))) +
  geom_line(aes(y = step)) +
  labs(title = "Step change",y = "Power", x = "Number of people per timepoint") +
  scale_color_discrete(name = "Effect size") +
  theme(legend.position = "none")


power2 <- df %>% 
  filter(N_t == 8) %>% 
  ggplot(aes(x = N_pers,  colour = as.factor(effect_sizes))) +
  geom_line(aes(y = slope), linetype = "dashed") +
  labs(title = "Slope change", y = "Power", x = "Number of people per timepoint") +
  scale_color_discrete(name = "Effect size") 

power1 + power2

ggsave("Output/figures/sp_per_n.png")

bias1 <- df %>% 
  filter(N_t == 8) %>% 
  ggplot(aes(x = N_pers,  colour = as.factor(effect_sizes))) +
  geom_line(aes(y = bias_step)) +
  labs(title = "Step change",y = "Bias", x = "Number of people per timepoint") +
  scale_color_discrete(name = "Effect size") +
  theme(legend.position = "none")


bias2 <- df %>% 
  filter(N_t == 8) %>% 
  ggplot(aes(x = N_pers,  colour = as.factor(effect_sizes))) +
  geom_line(aes(y = bias_slope), linetype = "dashed") +
  labs(title = "Slope change", y = "Bias", x = "Number of people per timepoint") +
  scale_color_discrete(name = "Effect size") 

bias1 + bias2

ggsave("Output/figures/sb_per_n.png")
```


### Another option for the simulation plot

```{r, echo=F, fig.height= 4, fig.width=6}
# figure of the sim studie
time <- rep(seq(10),3)
group <- c(rep("Step", 10), rep("Slope", 10), rep("Step and slope", 10))
score1 <- time * 2 + c(rep(0,5), rep(-2,5), rep(0,5), -0.5, -1.2, -2.2, -3.2, -4.2, rep(0, 5), 
                       -3, -4.5, -6, -7.5, -9)

data_eex <- data.frame(time = time, 
            group = group,
            score = score1)

P1 <- data_eex %>% 
  filter(group == "Step") %>% 
  ggplot(aes(x = time, y = score)) +
  geom_point() +
  geom_segment(aes(x = 1, y = 2, xend = 5.5, yend = 11)) +
  geom_segment(aes(x = 5.5, y = 9, xend = 10, yend = 18), color = "red") +
  guides(color="none") +
  ylim(0, 20) +
  labs(title = "Step", y = "Score", x = "Time") +
  geom_vline(xintercept = 5.5) +
  scale_x_continuous("Time", labels=c("T_0", "(N+1)/2", "T_N"), breaks=c(1, 5.5, 10)) +
  theme_classic()

P2 <- data_eex %>% 
  filter(group == "Slope") %>% 
  ggplot(aes(x = time, y = score)) +
  geom_point() +
  geom_segment(aes(x = 1, y = 2, xend = 5.5, yend = 11)) +
  geom_segment(aes(x = 5.5, y = 11, xend = 10, yend = 16), color = "green") +
  guides(color="none") +
  ylim(0, 20) +
  labs(title = "Slope", y = "Score", x = "Time") +
  geom_vline(xintercept = 5.5) +
  scale_x_continuous("Time", labels=c("T_0", "(N+1)/2", "T_N"), breaks=c(1, 5.5, 10)) +
  theme_classic()

P3 <- data_eex %>% 
  filter(group == "Step and slope") %>% 
  ggplot(aes(x = time, y = score)) +
  geom_point() +
  geom_segment(aes(x = 1, y = 2, xend = 5.5, yend = 11)) +
  geom_segment(aes(x = 5.5, y = 8.75, xend = 10, yend = 11),  color = "blue") +
  guides(color="none") +
  ylim(0, 20) +
  labs(title = "Step and slope", y = "Score", x = "Time") +
  geom_vline(xintercept = 5.5) +
  scale_x_continuous("Time", labels=c("T_0", "(N+1)/2", "T_N"), breaks=c(1, 5.5, 10)) +
  theme_classic()

P1 + P2 + P3

#ggsave("Output/figures/sim_setup1.png")
```


