---
title: "Sim_data"
author: "Florian van Leeuwen"
date: "9/16/2022"
output: pdf_document
---

```{r}
library(haven)
library(dplyr)
library(xtable)
library(simstudy)
```

# test data set
```{r}
# sim data 
set.seed(123)

# data example 1 intecept with constant slope and large SD
XS1 <- 1:100
cutoff2 <- c(20,40,60,80)
constant1 <- c(rep(0,20), rep(20,20),rep(0,20),rep(20,20),rep(0,20))
YS1 <- 10 + constant1 
YS1_2 <- 10 + constant1 + rnorm(100, mean = 0, sd =6)
data_S1 <- data.frame(X = XS1,Y = YS1, Y2 = YS1_2)

# data example 2 intercept no slope
XS2 <- 1:100
cutoff6 <- c(rep(0,20), rep(2,20), rep(0,20), rep(3,20), rep(0,20))
constant6 <- c(rep(0,20), rep(-40,20), rep(40,20), rep(-140,20), rep(100,20))
YS2 <- 10 + XS2 + XS2*cutoff6 + constant6 
YS2_2 <- 10 + XS2 + XS2*cutoff6 + constant6 +rnorm(100, mean = 0, sd =4)
data_S2 <- data.frame(X = XS2,Y = YS2, Y2 = YS2_2)

# data example 4 Different slopes time points
XS3 <- 1:50
cutoff5 <- c(rep(0,10), rep(2,10), rep(0,10), rep(4,10), rep(0,10))
constant2 <- c(rep(0,10), rep(0,10), rep(40,10), rep(-40,10), rep(120,10))
YS3 <- 10 + cutoff5*XS3 + constant2 
YS3_2 <- 10 + cutoff5*XS3 + constant2 +rnorm(50, mean = 0, sd =2) 
data_S3 <- data.frame(X = XS3,Y = YS3, Y2 = YS3_2)

# data example 3 intercept and slope and different lengths treatment
XS4 <- 1:140
cutoff4 <- c(rep(0,20), rep(2,10), rep(0,20), rep(2,30), rep(0,20), rep(2,20), rep(0,20))
constant <- c(rep(0,20), rep(0,10), rep(60,20), rep(0,30), rep(160,20),rep(0,20), rep(240,20))
YS4 <- 10 + cutoff4*XS4 + constant 
YS4_2 <- 10 + cutoff4*XS4 + constant +rnorm(140, mean = 0, sd =2) 
data_S4 <- data.frame(X = XS4,Y = YS4, Y2 = YS4_2)

data_sim <- tibble(
  Type = c("Intercept Period 1"," Δ Intercept Period 2"," Δ Intercept Period 3"," Δ Intercept Period 4"," Δ Intercept Period 5","Δ Intercept Period 6","Δ Intercept Period 7","Slope Period 1"," Δ Slope Period 2"," Δ Slope Period 3","Δ Slope Period 4","Δ Slope Period 5", "Δ Slope Period 6","Δ Slope Period 7"),
  M1 = c(c(10, 20, 0, 20, 0, "NA", "NA"), c(0,0,0,0,0, "NA", "NA")),
  M2 = c(c(10, 0, 0, 0, 0, "NA", "NA"),c(1,2,0,3,0, "NA", "NA")),
  M3 = c(c(10, 20, 0, 40, 0, "NA", "NA"),c(0,2,0,4,0, "NA", "NA")),
  M4 = c(c(10, 40, 0, 50, 0, 50,0), c(0, 2, 0, 2, 0, 2, 0)))

#print(xtable(data_sim, type = "latex"), file = "Example paramters.tex")

rm(constant, constant1, constant2, constant6, cutoff2, cutoff4, cutoff5, cutoff6,
   XS1, XS2, XS3, XS4, YS1, YS2, YS3, YS4, YS1_2, YS2_2, YS3_2, YS4_2)
```

```{r}

# add an indicator for the time periods and the lagged values
data_S1 <- data_S1 %>% 
  mutate(Period = as.factor(c(rep(0,20),rep(1,20),rep(2,20),rep(3,20),rep(4,20))),
         Time_since_X = rep(seq(1,20,1),5)) %>% 
  rename(Score = Y,
         Score2 = Y2,
         Time = X) %>% 
         mutate(Score_lag = lag(Score),
         Score2_lag = lag(Score2)) 

data_S2 <- data_S2 %>% 
  mutate(Period = as.factor(c(rep(0,20),rep(1,20),rep(2,20),rep(3,20),rep(4,20))),
         Time_since_X = rep(seq(1,20,1),5))%>% 
  rename(Score = Y,
         Score2 = Y2,
         Time = X)  %>% 
         mutate(Score_lag = lag(Score),
         Score2_lag = lag(Score2)) 

data_S3 <- data_S3 %>% 
  mutate(Period = as.factor(c(rep(0,10),rep(1,10),rep(2,10),rep(3,10),rep(4,10))),
         Time_since_X = rep(seq(1,10,1),5)) %>% 
  rename(Score = Y,
         Score2 = Y2,
         Time = X)  %>% 
         mutate(Score_lag = lag(Score),
         Score2_lag = lag(Score2)) 

data_S4 <- data_S4 %>% 
  mutate(Period = as.factor(c(rep(0,20), rep(1,10), rep(2,20), rep(3,30), rep(4,20), rep(5,20), rep(6,20))),
         Time_since_X = c(seq(1,20,1), seq(1,10,1), seq(1,20,1),seq(1,30,1), seq(1,20,1), seq(1,20,1), seq(1,20,1)))%>% 
  rename(Score = Y,
         Score2 = Y2,
         Time = X)  %>% 
         mutate(Score_lag = lag(Score),
         Score2_lag = lag(Score2)) 
```

# FUll data simulation
# to speed up process:
# https://www.r-bloggers.com/2017/02/make-your-r-simulation-models-20-times-faster/


```{r}
# esample of the data that is being simulated
set.seed(123)
def <- defData(varname = "Score1", dist = "normal", formula = 170, var = 25)
def <- defData(def, varname = "Score2", dist = "normal", formula = "170 + 12.7", var = 25)
def <- defData(def, varname = "Score3", dist = "normal", formula = "170 + 2*12.7", var = 25)
def <- defData(def, varname = "Score4", dist = "normal", formula = "170 + 3*12.7", var = 25)
def <- defData(def, varname = "Score5", dist = "normal", formula = "170 + 4*12.7 + 1", var = 25)
def <- defData(def, varname = "Score6", dist = "normal", formula = "170 + 5*12.7 + 1", var = 25)
def <- defData(def, varname = "Score7", dist = "normal", formula = "170 + 6*12.7 + 1 ", var = 25)
def <- defData(def, varname = "Score8", dist = "normal", formula = "170 + 7*12.7 + 1", var = 25)

dd <- genData(1000, def)

dd_long <- pivot_longer(data = dd, 
                                  cols = c(2:9))
dd_long <- dd_long %>% 
    mutate(treatment = rep(c(0,0,0,0,1,1,1,1), 1000),
            time = rep(seq(1,8,1), 1000))

dd_long %>% ggplot(aes(x = time, y = value, coloir = treatment)) + 
  geom_point()
```


```{r}
Cito_data_sim <- function(seed, N_person, N_sim, step_size, slope_size, N_time){
  # This is a function that simulates data and calculates the power of a segmented regression
  # alpha is set to 0.05
  
  #seed
  set.seed(seed)
  
  power_total <- list()
  N_t <- c()
  N_pers <- c()
  step <- c()
  slope <- c()
  
  # check the number of timepoints
  for (t in 1:length(N_time)){
  if (N_time[t] == 8){
        v_name <- c("Score2","Score3","Score4","Score5","Score6","Score7","Score8")
    form <- c("170 + 12.7","Score2 + 12.7","Score3 + 12.7",paste("Score4 + 12.7 +", step_size),paste("Score5 + 12.7 +", step_size),paste("Score6 + 12.7 +", step_size),paste("Score7 + 12.7 +", step_size))
    var <- c(27,27,26,26,26,25,25,25)
  }
    if (N_time[t] == 12){
        v_name <- c("Score2","Score3","Score4","Score5","Score6","Score7","Score8","Score9","Score10","Score11","Score12")
    form <- c("170 + 12.7","170 + 2*12.7","170 + 3*12.7","170 + 4*12.7","170 + 5*12.7",
              paste("170 + 6*12.7 +", step_size),paste("170 + 7*12.7 +", step_size),paste("170 + 8*12.7 +", step_size),paste("170 + 9*12.7 +", step_size),paste("170 + 10*12.7 +", step_size),paste("170 + 11*12.7 +", step_size))
    var <- c(27,27,26,26,26,25,25,25,25,25,25,25)
    }
    if (N_time[t] ==16){
        v_name <- c("Score2","Score3","Score4","Score5","Score6","Score7","Score8","Score9","Score10","Score11","Score12","Score13","Score14","Score15","Score16")
    form <- c("170 + 12.7","170 + 2*12.7","170 + 3*12.7","170 + 4*12.7","170 + 5*12.7", "170 + 6*12.7","170 + 7*12.7",
              paste("170 + 8*12.7 +", step_size),paste("170 + 9*12.7 +", step_size),paste("170 + 10*12.7 +", step_size),paste("170 + 11*12.7 +", step_size),paste("170 + 12*12.7 +", step_size),paste("170 + 13*12.7 +", step_size),paste("170 + 14*12.7 +", step_size),paste("170 + 15*12.7 +", step_size))
    var <- c(27,27,26,26,26,25,25,25,25,25,25,25,25,25,25,25)
    }
    if (N_time[t] == 20){
        v_name <- c("Score2","Score3","Score4","Score5","Score6","Score7","Score8","Score9","Score10","Score11","Score12","Score13","Score14","Score15","Score16","Score17","Score18","Score19","Score20")
    form <- c("170 + 12.7","170 + 2*12.7","170 + 3*12.7","170 + 4*12.7","170 + 5*12.7", "170 + 6*12.7","170 + 7*12.7", "170 + 8*12.7","170 + 9*12.7",
              paste("170 + 10*12.7 +", step_size),paste("170 + 11*12.7 +", step_size),paste("170 + 12*12.7 +", step_size),paste("170 + 13*12.7 +", step_size),paste("170 + 14*12.7 +", step_size),paste("170 + 15*12.7 +", step_size),paste("170 + 16*12.7 +", step_size),paste("170 + 17*12.7 +", step_size),paste("170 + 18*12.7 +", step_size),paste("170 + 19*12.7 +", step_size))
    var <- c(27,27,26,26,26,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25)
  }
  
  #empty lists
  step_power <- c()
  slope_power <- c()
  
    # loop for the options of N_person
     for (i in 1:(length(N_person))){
       
        #empty lists
        t_value_step <- rep(NA, N_sim)
        t_value_slope <- rep(NA, N_sim)
        significant_step <- rep(NA, N_sim)
        significant_slope <- rep(NA, N_sim)
       
        # loop for the number of data sets per option
      for (j in 1:N_sim) {

        # Define the data with the characteristics from the cito data
        def <- defData(varname = "Score1", dist = "normal", formula = 170,
          variance = 28)
        for (k in 1:length(v_name)){
        def <- defData(def, varname = v_name[k], dist = "normal", formula = form[k],
            variance = var[k])
        }
        
        # Generate a data set with N_people
        dd <- genData(N_person[i], def)
        
        # change df to long format and add a variable for time and a dummy for treatment
        if (N_time[t] == 8){
          dd_long <- pivot_longer(data = dd, 
                                  cols = c(2:9))
          dd_long <- dd_long %>% 
          mutate(treatment = rep(c(0,0,0,0,1,1,1,1), N_person[i]),
                 time = rep(seq(1,8,1), N_person[i]))
        }
        
        if (N_time[t] == 12){
          dd_long <- pivot_longer(data = dd, 
                                  cols = c(2:13))
          dd_long <- dd_long %>% 
          mutate(treatment = rep(c(0,0,0,0,0,0,1,1,1,1,1,1), N_person[i]),
                 time = rep(seq(1,12,1), N_person[i]))
        }
        
         if (N_time[t] == 16){
           dd_long <- pivot_longer(data = dd, 
                                  cols = c(2:17))
           dd_long <- dd_long %>% 
          mutate(treatment = rep(c(0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1), N_person[i]),
                 time = rep(seq(1,16,1), N_person[i]))
         }
  
         if (N_time[t] == 20){
           dd_long <- pivot_longer(data = dd, 
                                  cols = c(2:21))
           dd_long <- dd_long %>% 
          mutate(treatment = rep(c(0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1), N_person[i]),
                 time = rep(seq(1,20,1), N_person[i]))
        }
        
        # run the model
        model <- lm(value ~ time*treatment, data = dd_long)

        # Obtain the t-values
        t_value_step[j] <- summary(model)$coefficients[3,3]
        t_value_slope[j] <- summary(model)$coefficients[4,3]
        
        if (abs(t_value_step[j]) > 1.96){
         significant_step[j] <- 1
        }
         else{
           significant_step[j] <- 0
         }
        
        if (abs(t_value_slope[j]) > 1.96){
         significant_slope[j] <- 1
        }
         else{
           significant_slope[j] <- 0
         }
      }
  #empirical power

  step_power[i] <- mean(significant_step)
  slope_power[i] <- mean(significant_slope)
     }
  
  N_t <- append(N_t,rep(N_time[t], length(N_person)))
  N_pers <- append(N_pers, N_person)
  step <- append(step, step_power)
  slope <- append(slope, slope_power)
  }
  
  power <- data.frame(N_t = N_t,
                      N_pers = N_pers,
                      step = step, 
                      slope = slope)
  return(power)
}
```

```{r}
# run the model
seed <- 123
N_person <- c(50,100,150,200,250, 300, 350, 400, 450, 500)
N_sim <- 100
step_size <- 1
slope_size <- 1
N_time <- c(8,12,16,20)

# with effect 1
test <- Cito_data_sim2(seed, N_person, 100, step_size, slope_size, N_time)

# with effect 0
test2 <- Cito_data_sim2(seed, N_person, 100, 0, slope_size, N_time)

# heat map effect 1
test %>% 
  ggplot(aes(x = N_t, y = N_pers, fill = step)) +
  geom_tile() + 
  labs(main = "Power in 100 simulated data sets per option" ,x = "Number of time points", y = "Number of participants", fill="Power") +
  theme_minimal()

# heat map effect 0
test2 %>% 
  ggplot(aes(x = N_t, y = N_pers, fill = step)) +
  geom_tile() + 
  labs(x = "Number of time points", y = "Number of participants", fill="Power") +
  theme_minimal()
```

```{r}
# replicate the data from hawley
N_person2 <- c(100, 200, 400, 800, 1600, 3200, 6400)

test3 <- Cito_data_sim2(seed, N_person2, 100, step_size, slope_size, N_time)

test3 %>% 
  ggplot(aes(x = N_t, y = N_pers, fill = step)) +
  geom_tile() + 
  labs(main = "Power in 100 simulated data sets per option" ,x = "Number of time points", y = "Number of participants", fill="Power") +
  theme_minimal()


test4 <- Cito_data_sim_no_slope(seed, N_person2, 100, step_size, slope_size, N_time)

test4 %>% 
  ggplot(aes(x = N_t, y = N_pers, fill = step)) +
  geom_tile() + 
  labs(title = "Power in 100 simulated data sets per option" ,x = "Number of time points (8/12/16/20)", y = "Number of participants", fill="Power") +
  theme_minimal()

ggsave("sim_study.png")
```

```{r}
# error is abs verschil gemiddlede Bias, error, MSE
```


